Internal Server Error: /
Traceback (most recent call last):
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/apptrack/resume/views.py", line 9, in resume
    header = Header.objects.get(pk=1)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 301, in get
    num = len(clone)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 709, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 772, in execute_sql
    sql, params = self.as_sql()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 82, in as_sql
    out_cols, s_params = self.get_columns(with_col_aliases)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 227, in get_columns
    col_aliases)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 302, in get_default_columns
    r = '%s.%s' % (qn(alias), qn2(field.column))
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 60, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 15, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
Internal Server Error: /tracker/
Traceback (most recent call last):
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/apptrack/tracker/views.py", line 16, in index
    return render(request, 'tracker/index.html')
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 298, in render
    match = condition.eval(context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 867, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/base.py", line 585, in resolve
    obj = self.var.resolve(context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/template/base.py", line 765, in _resolve_lookup
    current = current[bit]
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/utils/functional.py", line 298, in _setup
    self._wrapped = self._setupfunc()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 18, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 140, in get_user
    user_id = request.session[SESSION_KEY]
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 47, in __getitem__
    return self._session[key]
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 173, in _get_session
    self._session_cache = self.load()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=timezone.now()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 301, in get
    num = len(clone)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 709, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 772, in execute_sql
    sql, params = self.as_sql()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 82, in as_sql
    out_cols, s_params = self.get_columns(with_col_aliases)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 227, in get_columns
    col_aliases)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 302, in get_default_columns
    r = '%s.%s' % (qn(alias), qn2(field.column))
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 60, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 15, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
